# main menu
# [[main]]
# name = "Home"
# url = ""
# weight = 1

# [[main]]
# name = "About"
# url = "about/"
#  weight = 2

# [[main]]
# weight = 3
# name = "Pages"
# hasChildren = true

#  [[main]]
#  parent = "Pages"
#  name = "Blog Details"
#  url = "blog/post-1/"
#  weight = 1
  

# footer menu
# [[footer]]
# name = "About"
# url = "about/"
# weight = 1

# [[footer]]
# name = "Blog"
# url = "blog/"
# weight = 2